[profile.default]
src = "src"
out = "out"
test = "test"
script = "script"
libs = ["lib"]
solc_version = "0.8.30"
evm_version = "prague"
optimizer = true
optimizer_runs = 1
via_ir = true
bytecode_hash = "none"
cbor_metadata = false
ffi = false

[fuzz]
runs = 256

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}", chain = 11155111 }
