// SPDX-License-Identifier: MIT
pragma solidity 0.8.30;

import { Test } from "forge-std/Test.sol";

import { Groth16Verifier } from "../src/recovery/zkemail/Groth16Verifier.sol";
import {
    EmailProofVerifier,
    IGroth16Verifier,
    EmailProof
} from "../src/recovery/zkemail/EmailProofVerifier.sol";

/// @notice Verifies a REAL proof — generated by our self-hosted prover from a real
///         DKIM-signed Gmail message — against a verifier built from the same
///         `v2.0.2-dev` zkey.
///
///         zkEmail's own deployed verifiers (Sepolia `0x3E5f…5716`, Base Sepolia
///         `0xc5Ba…2226`) both return false for this proof: their verification
///         keys come from older circuit builds. This test pins the pairing that
///         actually works.
contract RealEmailProofTest is Test {
    EmailProofVerifier internal verifier;

    function setUp() public {
        verifier = new EmailProofVerifier(IGroth16Verifier(address(new Groth16Verifier())));
    }

    function test_realProofFromSelfHostedProverVerifies() public view {
        EmailProof memory proof = EmailProof({
            domainName: "gmail.com",
            publicKeyHash: 0x280b10886d6d3cb6a9f870d942996b420bbfc51e3bd1f430e18690a6859b6d8f,
            timestamp: 1785017806,
            maskedCommand: "Recover account 0x232668A6920c397F5dFC0DEAEc064A7508B62d76 using recovery hash 0xb7120c0698aee965049348890af8a849549dca8aac0b632bdd76bd706b9083d8",
            emailNullifier: 0x265fb30a49f5348eb7dba6e01ecc9e9fd60815d6853fd454c8276b241c19cc19,
            accountSalt: 0x19bf410cbbf16ac09785715f7eeafb121f4edf152cc07c2e73aaef92af2338ad,
            isCodeExist: true,
            proof: hex"1ad70ed5c93235999e07ed175f61fa5fb0e5ea1db02a0cfba54cd0cecb585b2b1abb7cd1eb65dd057f773742ccf2dfc1965eaa1903fe3d730cf5a53c65e988911cf78c1f71cd75e045c03a41319dc0eb2a49074351af2b1601abb1fcffdc57ac2ed60ab7df1cfa576ccd88322b57c26c85176ad9117ed9ae43ecdad1f50d577b050c6d7a7563efc0b9759b31a1e397e6cde3dbf4c3eea8df622d9764395628d10839663d1da42b8f2fd20844aeb6087f90a26e0f32571f558be172f29d4ceace08b31e4282ff7b6c64926e81597d0e55e67ca9ae27dfe042f1b623b8b0424c0012aa867233bebf9367c52ba6cfd9fba210dc9022faa9f1b3948704478479ad53"
        });

        assertTrue(
            verifier.verifyEmailProof(proof),
            "real proof rejected: Groth16Verifier does not match the prover's zkey"
        );
    }
}
